application: ironpuzzler-1086
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /admin/js
  static_dir: admin_js

- url: /admin.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

inbound_services:
- channel_presence
