application: ironpuzzler
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /admin/js
  static_dir: admin_js

- url: /.*
  script: _go_app
